import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

/**
 * Collapse whitespace runs to one space between tags and inside tags (attribute runs), leaving text nodes inside
 * <text> elements and inside any element carrying xml:space="preserve" untouched, so glyph spacing in labels survives.
 */
export function collapseSvg(svg) {
  const stack = []; let preserve = 0, out = '';
  for (const tok of svg.replace(/<!--[\s\S]*?-->/g, '').split(/(<[^>]+>)/)) {   // comments never ship
    if (!tok) continue;
    if (!tok.startsWith('<')) { out += preserve ? tok : tok.replace(/\s+/g, ' '); continue; }
    out += tok.replace(/\s+/g, ' ');
    if (tok.startsWith('</')) { const p = stack.pop(); if (p) preserve -= p; continue; }
    if (tok.endsWith('/>') || tok.startsWith('<?') || tok.startsWith('<!')) continue;
    const name = /^<([\w:-]+)/.exec(tok)?.[1];
    const keep = name === 'text' || /\sxml:space="preserve"/.test(tok) ? 1 : 0;
    stack.push(keep); preserve += keep;
  }
  return out.trim();
}

export function embedAll(src = 'assets/cels', out = 'src/render/cels') {
  mkdirSync(out, { recursive: true });
  for (const f of readdirSync(src).filter(f => f.endsWith('.svg'))) {
    const id = f.replace('.svg', ''); const name = id.toUpperCase().replace(/-/g, '_') + '_CEL';
    const svg = collapseSvg(readFileSync(join(src, f), 'utf8'));
    writeFileSync(join(out, `${id}.ts`), `// generated by tools/embed-cels.mjs from ${src}/${f} — do not edit\nexport const ${name} = ${JSON.stringify(svg)};\n`);
    console.log('embedded', f, '→', `${out}/${id}.ts`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) embedAll();
