import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
const src = 'assets/cels', out = 'src/render/cels'; mkdirSync(out, { recursive: true });
for (const f of readdirSync(src).filter(f => f.endsWith('.svg'))) {
  const id = f.replace('.svg', ''); const name = id.toUpperCase().replace(/-/g, '_') + '_CEL';
  const svg = readFileSync(join(src, f), 'utf8').replace(/\s+/g, ' ').trim();
  writeFileSync(join(out, `${id}.ts`), `// generated by tools/embed-cels.mjs from ${src}/${f} — do not edit\nexport const ${name} = ${JSON.stringify(svg)};\n`);
  console.log('embedded', f, '→', `${out}/${id}.ts`);
}
